# Travis build integration.
# https://docs.travis-ci.com/

language: c

os:
  - linux

compiler:
  - gcc
  - clang

notifications:
  irc:
    channels:
      - "irc.freenode.org#openrc"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

script:
  - ./test/travis.sh
